feat: surround region and mcid with atmark
GiganticMinecraft/ObserverUtils pull request #62
Opened 2023-03-04 09:49 UTC by mel9y

close #60

2023-03-04 09:58 UTC, Lucky3028 approved these changes
ありがとうございます！

2023-03-04 09:58 UTC, Lucky3028 requested changes

2023-03-04 09:58 UTC, Lucky3028 commented on src/main/kotlin/click/seichi/observerutils/commands/Command.kt
>                      |_.重複保護|$duplicatedRegions|
ここも囲っていただいてもいいですか？

2023-03-04 09:59 UTC, Lucky3028 commented on src/main/kotlin/click/seichi/observerutils/commands/Command.kt
>                      |_.重複保護|$duplicatedRegions|
わかりにくいな
ここっていうのは、重複保護の各保護名です

2023-03-04 10:00 UTC, Lucky3028 commented on src/main/kotlin/click/seichi/observerutils/commands/Command.kt
>                      |_.重複保護|$duplicatedRegions|
なので、l.60ですね

2023-03-05 05:33 UTC, mel9y commented on src/main/kotlin/click/seichi/observerutils/commands/Command.kt
>                      |_.重複保護|$duplicatedRegions|
こんな感じで大丈夫ですか?

https://github.com/GiganticMinecraft/ObserverUtils/pull/62/commits/09ea1e1a70c2ee1d3c848f5dabebfee3ea06fd02

2023-03-05 06:44 UTC, Lucky3028 commented on src/main/kotlin/click/seichi/observerutils/commands/Command.kt
>                      |_.重複保護|$duplicatedRegions|
そうではなく、l.60でString[]をStringにjoinしているので、そのタイミングで各保護名に対して`@@`をつけていただけると

2023-03-05 11:30 UTC, Lucky3028 requested changes
そうではなくこうですね
言い方が悪かったです、すみません

2023-03-05 11:30 UTC, Lucky3028 commented on src/main/kotlin/click/seichi/observerutils/commands/Command.kt
> +                    if (regions.size >= 2) "(${regions.size}): @@${regions.joinToString { it.id }}@@" else "-"
```suggestion
                    if (regions.size >= 2) "(${regions.size}): ${regions.joinToString { "@@${it.id}@@" }}" else "-"
```

2023-03-05 11:35 UTC, Lucky3028 requested changes

2023-03-05 11:35 UTC, Lucky3028 commented on src/main/kotlin/click/seichi/observerutils/commands/Command.kt
> +                    if (regions.size >= 2) "(${regions.size}): @@${regions.joinToString { it.id }}@@" else "-"
```suggestion
                    if (regions.size == 1) "-" else "(${regions.size}): ${regions.joinToString { "@@${it.id}@@" }}"
```
もっと言えばこっちのほうがシンプルですね。自分のコードですけど...。

2023-03-07 13:29 UTC, Lucky3028 approved these changes

2023-03-07 13:30 UTC, merged